###############

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'DuINet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16               
  NUM_EPOCHS: 100
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 128
  RESUME: False
  WARMUP: True
  TRAIN_DIR: './patches/real/train' # path to training data
  VAL_DIR: './patches/real/val'     # path to validation data
  SAVE_DIR: './checkpoints/DuINet'  # path to save models and images 
  SAVE_IMAGES: False
  #VAL_AFTER_EVERY: 1
